# -*- coding: utf-8 -*-
"""Agenda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWdn7OpFZdyVJRmP4KKtUjczzn2BJrCH
"""

class Agenda:

  def tela(self):
    print('''Bem vindo à sua Agenda Python.
    [1] Adicionar um número
    [2] Adicionar aos favoritos
    [3] Adicionar e-mail
    [4] Ver a lista de números
    [5] Ver a lista dos favoritos
    [6] Remover contato
    [7] Remover favorito
    [8] Editar contato
    [0] Sair
    ''')

  def addnumero(self, contatos):
    try:
      numero = input("Insira o número que deseja adicionar ao seu celular: ")
      nome = input("Digite o nome da pessoa para salvar o número: ")
      contatos[nome] = {"numero": numero, "email": ""}
      print(f"{nome} adicionado com sucesso")
    except Exception as e:
      print(f"Erro: {e}. Tente novamente.")

  def listacontatos(self, contatos):
    if not contatos:
      print("Você é solitário")
      return
    print("\nContatos:")
    for nome, dados in contatos.items():
      print(f"- {nome}: Número: {dados['numero']}, Email: {dados['email'] if dados['email'] else 'Não informado'}")

  def addfav(self, contatos, favoritos):
    if not contatos:
      print("Você não possui nenhum contato")
      return
    nomefav = input("Digite o contato para adicionar aos favoritos: ")
    if nomefav in contatos:
      favoritos[nomefav] = contatos[nomefav]
      print(f"{nomefav} adicionado aos favoritos")
    else:
      print("Contato não encontrado.")

  def listafav(self, favoritos):
    if not favoritos:
      print("Você não possui nenhum contato favorito")
      return

    print("\nFavoritos:")
    for nome, dados in favoritos.items():
      print(f"- {nome}: Número: {dados['numero']}, Email: {dados['email'] if dados['email'] else 'Não informado'}")

  def RemoverContato(self, contatos):
    if not contatos:
      print("Você não possui nenhum contato para remover.")
      return
    nome_remover = input("Digite o nome do contato que deseja remover: ")
    if nome_remover in contatos:
      del contatos[nome_remover]
      print(f"Contato '{nome_remover}' removido com sucesso.")
    else:
      print("Contato não encontrado.")

  def addemail(self, contatos):
      if not contatos:
          print("Você não possui nenhum contato.")
          return
      nome_contato = input("Digite o nome do contato para adicionar o e-mail: ")
      if nome_contato in contatos:
          email = input("Digite o e-mail: ")
          contatos[nome_contato]["email"] = email
          print(f"E-mail adicionado para {nome_contato}.")
      else:
          print("Contato não encontrado.")

  def RemoverFav(self, favoritos):
    if not favoritos:
      print("Você não possui nenhum contato para remover.")
      return
    favremover = input("Digite o nome do contato que deseja remover: ")
    if favremover in favoritos:
      del favoritos[favremover]
      print(f"Contato '{favremover}' removido com sucesso.")
    else:
      print("Contato não encontrado.")

  def editContato(self, contatos):
    if not contatos:
      print("Você não possui contatos para editar.")
      return
    nomevelho = input("Digite o nome do contato que deseja editar: ")
    if nomevelho in contatos:
      print("O que deseja editar?")
      print("[1] Nome")
      print("[2] Número")
      print("[3] E-mail")
      opcao = input("Escolha uma opção: ")
      if opcao == '1':
        novonome = input("Digite o novo nome: ")
        contatos[novonome] = contatos.pop(nomevelho)
        print("Nome atualizado com sucesso.")
      elif opcao == '2':
        novonumero = input("Digite o novo número: ")
        contatos[nomevelho]['numero'] = novonumero
        print("Número atualizado com sucesso.")
      elif opcao == '3':
        novoemail = input("Digite o novo e-mail: ")
        contatos[nomevelho]['email'] = novoemail
        print("E-mail atualizado com sucesso.")
      else:
        print("Opção inválida.")
    else:
      print("Contato não encontrado.")

def main():
  agenda = Agenda()
  contatos = {}
  favoritos = {}
  agenda.tela()
  while True:
    try:
      opcao = input("Selecione uma das opções (ou 'sair' para desligar): ")
      if opcao == '1':
        agenda.addnumero(contatos)
      elif opcao == '2':
        agenda.addfav(contatos, favoritos)
      elif opcao == '3':
        agenda.addemail(contatos)
      elif opcao == '4':
        agenda.listacontatos(contatos)
      elif opcao == '5':
        agenda.listafav(favoritos)
      elif opcao == '6':
        agenda.RemoverContato(contatos)
      elif opcao == '7':
        agenda.RemoverFav(favoritos)
      elif opcao == '8':
        agenda.editContato(contatos)
      elif opcao == '0' or opcao.lower() == 'sair':
        print("Até logo")
        break
      else:
        print("Digite uma opção válida")
    except Exception as e:
      print(f"Ocorreu um erro: {e}")

main()